CREATE DATABASE desafiofabrica;
USE desafiofabrica;

CREATE TABLE NOTAS (
NOME VARCHAR (100), NOTA1 INT, NOTA2 INT, NOTA3 INT);

SELECT * FROM NOTAS; 
INSERT INTO NOTAS (NOME, NOTA1, NOTA2, NOTA3)
VALUES ("VICTOR", "7", "4", "8");

CREATE TABLE PAGAMENTOS(
NOME VARCHAR (100), DATA_N DATE, PAGO VARCHAR(100));

SELECT * FROM PAGAMENTOS; 
INSERT INTO PAGAMENTOS (NOME, DATA_N, PAGO)
VALUES ("MARIA", "1998-09-12", "NAO");


DELETE FROM PAGAMENTOS WHERE DATA_N = "000-00-00";


